---
- 影音:
    - Jellyfin:
        href: http://raspberrypi.local:8096
        description: 媒体播放
    - Jellyseerr:
        href: http://raspberrypi.local:5055
        description: 点播入口
    - Radarr:
        href: http://raspberrypi.local:7878
        description: 电影管理
    - qBittorrent:
        href: http://raspberrypi.local:8085
        description: BT 下载
    - Bazarr:
        href: http://raspberrypi.local:6767
        description: 字幕管理
    - Jackett:
        href: http://raspberrypi.local:9117
        description: 索引聚合
    - ChineseSubFinder:
        href: http://raspberrypi.local:19035
        description: 中文字幕补充

- 系统:
    - Homepage:
        href: https://raspberrypi.local/
        description: 本导航页
    - Vaultwarden:
        href: http://raspberrypi.local:8001
        description: 密码管理
    - AdGuard Home:
        href: http://raspberrypi.local:3000
        description: DNS 去广告
    - Portainer:
        href: https://raspberrypi.local:9443
        description: 容器管理
